# superuser needed to run then rest 
language: generic
sudo: required
# Need docker service installed
services:
  - docker

# what needs to be done before running 
# build an image using dockerfile.dev
before_install:
  - docker build -t angry-panda -f Dockerfile.dev . 

#commands to run
# CI=true sets the test to run in CI mode so as not to start the watcher
script:
  - docker run -e  CI=true angry-panda npm run test

