#  volumes, map tje /app/nodemodules to itself while mapping current file. to /app
# Since our dockerfile is dockerfile.dev we define it in the build context
# context: . would have been /ourprojectfolder, if the file was in this folder
version: '3'

services:
  angry-panda:
    build: 
      context: .
      dockerfile: Dockerfile.dev      
    ports:
      - "80:3000"
    volumes:
      - /app/node_modules
      - .:/app

  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
      
