FROM node

ARG USER=sabonis
# RUN groupadd -r ${USER} && useradd --no-log-init -r -g ${USER} ${USER}

ARG USER_ID=1001
ARG GROUP_ID=1001


RUN groupadd -g ${GROUP_ID} ${USER} && useradd -u ${USER_ID} -g ${USER} -s /bin/sh ${USER}

WORKDIR /home/app

COPY package.json .
RUN npm install




# while docker-compose has the volume .:/app part this is not necessary
COPY . .

RUN chown -R ${USER}:${USER} /home/app
RUN chmod 755 /root

CMD ["npm", "run", "start"]
